import Foundation

class MDMProfileGenerator {
    static let shared = MDMProfileGenerator()
    
    private init() {}
    
    // MARK: - Profile Generation
    
    func generateWiFiProfile(ssid: String, password: String? = nil) -> String {
        var profile = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>PayloadContent</key>
            <array>
                <dict>
                    <key>PayloadType</key>
                    <string>com.apple.wifi.managed</string>
                    <key>PayloadVersion</key>
                    <integer>1</integer>
                    <key>PayloadIdentifier</key>
                    <string>com.jarvis.wifi.\(UUID().uuidString)</string>
                    <key>PayloadDisplayName</key>
                    <string>Wi-Fi Configuration</string>
                    <key>PayloadDescription</key>
                    <string>Configures Wi-Fi settings</string>
                    <key>PayloadUUID</key>
                    <string>\(UUID().uuidString)</string>
                    <key>AutoJoin</key>
                    <true/>
                    <key>EncryptionType</key>
                    <string>\(password != nil ? "WPA" : "None")</string>
                    <key>HIDDEN_NETWORK</key>
                    <false/>
                    <key>SSID_STR</key>
                    <string>\(ssid)</string>
        """
        
        if let password = password {
            profile += """
                    <key>Password</key>
                    <string>\(password)</string>
            """
        }
        
        profile += """
                </dict>
            </array>
            <key>PayloadOrganization</key>
            <string>Jarvis</string>
            <key>PayloadDisplayName</key>
            <string>Jarvis Wi-Fi Profile</string>
            <key>PayloadVersion</key>
            <integer>1</integer>
            <key>PayloadUUID</key>
            <string>\(UUID().uuidString)</string>
            <key>PayloadIdentifier</key>
            <string>com.jarvis.wifi.profile</string>
            <key>PayloadDescription</key>
            <string>Wi-Fi configuration profile generated by Jarvis</string>
            <key>PayloadType</key>
            <string>Configuration</string>
        </dict>
        </plist>
        """
        
        return profile
    }
    
    func generateVPNProfile(server: String, account: String, password: String) -> String {
        return """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>PayloadContent</key>
            <array>
                <dict>
                    <key>PayloadType</key>
                    <string>com.apple.vpn.managed</string>
                    <key>PayloadVersion</key>
                    <integer>1</integer>
                    <key>PayloadIdentifier</key>
                    <string>com.jarvis.vpn.\(UUID().uuidString)</string>
                    <key>PayloadDisplayName</key>
                    <string>VPN Configuration</string>
                    <key>PayloadDescription</key>
                    <string>Configures VPN settings</string>
                    <key>PayloadUUID</key>
                    <string>\(UUID().uuidString)</string>
                    <key>VPNType</key>
                    <string>IPSec</string>
                    <key>VPNSubType</key>
                    <string>Cisco</string>
                    <key>VPNIdentifier</key>
                    <string>com.jarvis.vpn</string>
                    <key>RemoteAddress</key>
                    <string>\(server)</string>
                    <key>AuthenticationMethod</key>
                    <string>Password</string>
                    <key>LocalIdentifier</key>
                    <string>\(account)</string>
                    <key>LocalIdentifierType</key>
                    <string>KeyID</string>
                    <key>XAuthEnabled</key>
                    <integer>1</integer>
                    <key>XAuthName</key>
                    <string>\(account)</string>
                    <key>XAuthPassword</key>
                    <string>\(password)</string>
                    <key>PayloadEnabled</key>
                    <true/>
                </dict>
            </array>
            <key>PayloadOrganization</key>
            <string>Jarvis</string>
            <key>PayloadDisplayName</key>
            <string>Jarvis VPN Profile</string>
            <key>PayloadVersion</key>
            <integer>1</integer>
            <key>PayloadUUID</key>
            <string>\(UUID().uuidString)</string>
            <key>PayloadIdentifier</key>
            <string>com.jarvis.vpn.profile</string>
            <key>PayloadDescription</key>
            <string>VPN configuration profile generated by Jarvis</string>
            <key>PayloadType</key>
            <string>Configuration</string>
        </dict>
        </plist>
        """
    }
    
    func generateRestrictionsProfile() -> String {
        return """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>PayloadContent</key>
            <array>
                <dict>
                    <key>PayloadType</key>
                    <string>com.apple.applicationaccess</string>
                    <key>PayloadVersion</key>
                    <integer>1</integer>
                    <key>PayloadIdentifier</key>
                    <string>com.jarvis.restrictions.\(UUID().uuidString)</string>
                    <key>PayloadDisplayName</key>
                    <string>Device Restrictions</string>
                    <key>PayloadDescription</key>
                    <string>Configures device restrictions</string>
                    <key>PayloadUUID</key>
                    <string>\(UUID().uuidString)</string>
                    <key>allowAppInstallation</key>
                    <false/>
                    <key>allowCamera</key>
                    <false/>
                    <key>allowScreenShot</key>
                    <false/>
                    <key>forceAirPlayIncomingRequestsPairingPassword</key>
                    <true/>
                    <key>allowExplicitContent</key>
                    <false/>
                </dict>
            </array>
            <key>PayloadOrganization</key>
            <string>Jarvis</string>
            <key>PayloadDisplayName</key>
            <string>Jarvis Restrictions Profile</string>
            <key>PayloadVersion</key>
            <integer>1</integer>
            <key>PayloadUUID</key>
            <string>\(UUID().uuidString)</string>
            <key>PayloadIdentifier</key>
            <string>com.jarvis.restrictions.profile</string>
            <key>PayloadDescription</key>
            <string>Restrictions profile generated by Jarvis</string>
            <key>PayloadType</key>
            <string>Configuration</string>
        </dict>
        </plist>
        """
    }
    
    // MARK: - Profile Management
    
    func saveProfileToFile(_ profile: String, filename: String) -> URL? {
        guard let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return nil
        }
        
        let fileURL = documentsDirectory.appendingPathComponent(filename)
        
        do {
            try profile.write(to: fileURL, atomically: true, encoding: .utf8)
            return fileURL
        } catch {
            print("Error saving profile: \(error)")
            return nil
        }
    }
    
    func installProfile(_ profileData: Data) {
        // In einer echten App würde hier die mobileconfig Datei an das System übergeben werden
        // Dies erfordert spezielle Berechtigungen und MDM-Registration
        print("Profile installation would be handled by MDM framework")
    }
}